# coding: utf-8

"""
    Azure Machine Learning - Text Analytics

    The Text Analytics API is a suite of text analytics web services built with Azure Machine Learning.   The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection.   No training data is needed to use this API; just bring your text data.   This API uses advanced natural language processing techniques to deliver best in class predictions.    Further documentation can be found in https://docs.microsoft.com/en-us/azure/cognitive-services/cognitive-services-text-analytics-quick-start

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.batch_input_v2 import BatchInputV2
from .models.detected_language_v2 import DetectedLanguageV2
from .models.error_record_v2 import ErrorRecordV2
from .models.error_response import ErrorResponse
from .models.input_v2 import InputV2
from .models.internal_error import InternalError
from .models.key_phrase_batch_result_item_v2 import KeyPhraseBatchResultItemV2
from .models.key_phrase_batch_result_v2 import KeyPhraseBatchResultV2
from .models.language_batch_result_item_v2 import LanguageBatchResultItemV2
from .models.language_batch_result_v2 import LanguageBatchResultV2
from .models.multi_language_batch_input_v2 import MultiLanguageBatchInputV2
from .models.multi_language_input_v2 import MultiLanguageInputV2
from .models.object import Object
from .models.operation_processing_result import OperationProcessingResult
from .models.operation_result import OperationResult
from .models.sentiment_batch_result_item_v2 import SentimentBatchResultItemV2
from .models.sentiment_batch_result_v2 import SentimentBatchResultV2
from .models.topic_assignment_record_v2 import TopicAssignmentRecordV2
from .models.topic_detection_input_v2 import TopicDetectionInputV2
from .models.topic_detection_result_v2 import TopicDetectionResultV2
from .models.topic_info_record_v2 import TopicInfoRecordV2

# import apis into sdk package
from .apis.default_api import DefaultApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
