# coding: utf-8

"""
    Azure Machine Learning - Text Analytics

    The Text Analytics API is a suite of text analytics web services built with Azure Machine Learning.   The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection.   No training data is needed to use this API; just bring your text data.   This API uses advanced natural language processing techniques to deliver best in class predictions.    Further documentation can be found in https://docs.microsoft.com/en-us/azure/cognitive-services/cognitive-services-text-analytics-quick-start

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TopicInfoRecordV2(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, score=None, key_phrase=None):
        """
        TopicInfoRecordV2 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'score': 'float',
            'key_phrase': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'score': 'score',
            'key_phrase': 'keyPhrase'
        }

        self._id = id
        self._score = score
        self._key_phrase = key_phrase

    @property
    def id(self):
        """
        Gets the id of this TopicInfoRecordV2.
        A unique identifier for each topic.

        :return: The id of this TopicInfoRecordV2.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TopicInfoRecordV2.
        A unique identifier for each topic.

        :param id: The id of this TopicInfoRecordV2.
        :type: str
        """

        self._id = id

    @property
    def score(self):
        """
        Gets the score of this TopicInfoRecordV2.
        Count of documents assigned to topic.

        :return: The score of this TopicInfoRecordV2.
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """
        Sets the score of this TopicInfoRecordV2.
        Count of documents assigned to topic.

        :param score: The score of this TopicInfoRecordV2.
        :type: float
        """

        self._score = score

    @property
    def key_phrase(self):
        """
        Gets the key_phrase of this TopicInfoRecordV2.
        A summarizing word or phrase for the topic.

        :return: The key_phrase of this TopicInfoRecordV2.
        :rtype: str
        """
        return self._key_phrase

    @key_phrase.setter
    def key_phrase(self, key_phrase):
        """
        Sets the key_phrase of this TopicInfoRecordV2.
        A summarizing word or phrase for the topic.

        :param key_phrase: The key_phrase of this TopicInfoRecordV2.
        :type: str
        """

        self._key_phrase = key_phrase

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TopicInfoRecordV2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
