# coding: utf-8

"""
    Azure Machine Learning - Text Analytics

    The Text Analytics API is a suite of text analytics web services built with Azure Machine Learning.   The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection.   No training data is needed to use this API; just bring your text data.   This API uses advanced natural language processing techniques to deliver best in class predictions.    Further documentation can be found in https://docs.microsoft.com/en-us/azure/cognitive-services/cognitive-services-text-analytics-quick-start

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TopicAssignmentRecordV2(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, document_id=None, topic_id=None, distance=None):
        """
        TopicAssignmentRecordV2 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'document_id': 'str',
            'topic_id': 'str',
            'distance': 'float'
        }

        self.attribute_map = {
            'document_id': 'documentId',
            'topic_id': 'topicId',
            'distance': 'distance'
        }

        self._document_id = document_id
        self._topic_id = topic_id
        self._distance = distance

    @property
    def document_id(self):
        """
        Gets the document_id of this TopicAssignmentRecordV2.
        Identifier for the document. Equates to the ID included in the input.

        :return: The document_id of this TopicAssignmentRecordV2.
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """
        Sets the document_id of this TopicAssignmentRecordV2.
        Identifier for the document. Equates to the ID included in the input.

        :param document_id: The document_id of this TopicAssignmentRecordV2.
        :type: str
        """

        self._document_id = document_id

    @property
    def topic_id(self):
        """
        Gets the topic_id of this TopicAssignmentRecordV2.
        The topic ID which the document has been assigned to.

        :return: The topic_id of this TopicAssignmentRecordV2.
        :rtype: str
        """
        return self._topic_id

    @topic_id.setter
    def topic_id(self, topic_id):
        """
        Sets the topic_id of this TopicAssignmentRecordV2.
        The topic ID which the document has been assigned to.

        :param topic_id: The topic_id of this TopicAssignmentRecordV2.
        :type: str
        """

        self._topic_id = topic_id

    @property
    def distance(self):
        """
        Gets the distance of this TopicAssignmentRecordV2.
        Document-to-topic affiliation score between 0 and 1. The lower a distance score the stronger the topic affiliation is.

        :return: The distance of this TopicAssignmentRecordV2.
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """
        Sets the distance of this TopicAssignmentRecordV2.
        Document-to-topic affiliation score between 0 and 1. The lower a distance score the stronger the topic affiliation is.

        :param distance: The distance of this TopicAssignmentRecordV2.
        :type: float
        """

        self._distance = distance

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TopicAssignmentRecordV2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
